config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  mount Sidekiq::Web => '/sidekiq' if defined?(Sidekiq)

  root 'dashboard#index'

  get 'up' => 'rails/health#show'

  devise_for :users,
             path: '/', only: %i[sessions passwords omniauth_callbacks],
             controllers: begin
               options = { sessions: 'sessions', passwords: 'passwords' }
               options[:omniauth_callbacks] = 'omniauth_callbacks' if User.devise_modules.include?(:omniauthable)
               options
             end

  devise_scope :user do
    resource :invitation, only: %i[update] do
      get '' => :edit
    end
  end

  namespace :api, defaults: { format: :json } do
    resources :attachments, only: %i[create]
    resources :submitters_autocomplete, only: %i[index]
    resources :template_folders_autocomplete, only: %i[index]
    resources :submitter_email_clicks, only: %i[create]
    resources :submitter_form_views, only: %i[create]
    resources :submitters, only: %i[index show update]
    resources :submissions, only: %i[index show create destroy] do
      collection do
        resources :emails, only: %i[create], controller: 'submissions', as: :submissions_emails
      end
    end
    resources :templates, only: %i[update show index destroy] do
      resources :clone, only: %i[create], controller: 'templates_clone'
      resources :submissions, only: %i[index create]
      resources :documents, only: %i[create], controller: 'templates_documents'
    end
  end

  resources :verify_pdf_signature, only: %i[create]
  resource :mfa_setup, only: %i[show new edit create destroy], controller: 'mfa_setup'
  resources :account_configs, only: %i[create]
  resources :user_configs, only: %i[create]
  resources :encrypted_user_configs, only: %i[destroy]
  resources :timestamp_server, only: %i[create]
  resources :dashboard, only: %i[index]
  resources :setup, only: %i[index create]
  resource :newsletter, only: %i[show update]
  resources :enquiries, only: %i[create]
  resources :users, only: %i[new create edit update destroy]
  resource :user_signature, only: %i[edit update destroy]
  resources :submissions, only: %i[show destroy]
  resources :console_redirect, only: %i[index]
  resource :testing_account, only: %i[show destroy]
  resources :testing_api_settings, only: %i[index]
  resource :templates_upload, only: %i[create]
  authenticated do
    resource :templates_upload, only: %i[show], path: 'new'
  end
  resources :templates_archived, only: %i[index], path: 'archived'
  resources :folders, only: %i[show edit update destroy], controller: 'template_folders'
  resources :template_sharings_testing, only: %i[create]
  resources :templates, only: %i[new create edit show destroy] do
    resources :restore, only: %i[create], controller: 'templates_restore'
    resources :archived, only: %i[index], controller: 'templates_archived_submissions'
    resources :submissions, only: %i[new create]
    resource :folder, only: %i[edit update], controller: 'templates_folders'
    resource :preview, only: %i[show], controller: 'templates_preview'
    resource :code_modal, only: %i[show], controller: 'templates_code_modal'
    resources :submissions_export, only: %i[index new]
  end
  resources :preview_document_page, only: %i[show], path: '/preview/:signed_uuid'
  resource :blobs_proxy, only: %i[show], path: '/blobs_proxy/:signed_uuid/*filename',
                         controller: 'api/active_storage_blobs_proxy'

  if Docuseal.multitenant?
    resource :blobs_proxy_legacy, only: %i[show],
                                  path: '/blobs/proxy/:signed_id/*filename',
                                  controller: 'api/active_storage_blobs_proxy_legacy',
                                  as: :rails_blob
    get '/disk/:encoded_key/*filename' => 'active_storage/disk#show', as: :rails_disk_service
    put '/disk/:encoded_token' => 'active_storage/disk#update', as: :update_rails_disk_service
    post '/direct_uploads' => 'active_storage/direct_uploads#create', as: :rails_direct_uploads
  end

  resources :start_form, only: %i[show update], path: 'd', param: 'slug' do
    get :completed
  end

  resources :submit_form, only: %i[], path: '' do
    get :success, on: :collection
  end

  resources :submit_form, only: %i[show update], path: 's', param: 'slug' do
    get :completed
  end

  resources :submissions_preview, only: %i[show], path: 'e', param: 'slug' do
    get :completed
  end

  resources :send_submission_email, only: %i[create] do
    get :success, on: :collection
  end

  resources :submitters, only: %i[], param: 'slug' do
    resources :download, only: %i[index], controller: 'submissions_download'
    resources :send_email, only: %i[create], controller: 'submitters_send_email'
    resources :debug, only: %i[index], controller: 'submissions_debug' if Rails.env.development?
  end

  scope '/settings', as: :settings do
    unless Docuseal.multitenant?
      resources :storage, only: %i[index create], controller: 'storage_settings'
      resources :email, only: %i[index create], controller: 'email_smtp_settings'
      resources :sms, only: %i[index], controller: 'sms_settings'
      resources :sso, only: %i[index], controller: 'sso_settings'
    end
    resources :notifications, only: %i[index create], controller: 'notifications_settings'
    resource :esign, only: %i[show create new update destroy], controller: 'esign_settings'
    resources :users, only: %i[index]
    resource :personalization, only: %i[show create], controller: 'personalization_settings'
    resources :api, only: %i[index create], controller: 'api_settings'
    resource :webhooks, only: %i[show create update], controller: 'webhook_settings'
    resource :account, only: %i[show update destroy]
    resources :profile, only: %i[index] do
      collection do
        patch :update_contact
        patch :update_password
        patch :update_app_url
      end
    end
  end

  ActiveSupport.run_load_hooks(:routes, self)
end

app/controllers/esign_settings_controller.rb
# frozen_string_literal: true

class EsignSettingsController < ApplicationController
  DEFAULT_CERT_NAME = 'DocuSeal Self-Host Autogenerated'

  CertFormRecord = Struct.new(:name, :file, :password, keyword_init: true) do
    include ActiveModel::Validations

    def to_key
      []
    end
  end

  before_action :load_encrypted_config
  authorize_resource :encrypted_config, parent: false, only: %i[new create]
  authorize_resource :encrypted_config, only: %i[update destroy show]

  def show
    cert_data = @encrypted_config.value || {}

    default_pkcs = GenerateCertificate.load_pkcs(cert_data) if cert_data['cert'].present?

    custom_pkcs_list = (cert_data['custom'] || []).map do |e|
      { 'pkcs' => OpenSSL::PKCS12.new(Base64.urlsafe_decode64(e['data']), e['password'].to_s),
        'name' => e['name'],
        'status' => e['status'] }
    end

    @pkcs_list = [
      if default_pkcs
        {
          'pkcs' => default_pkcs,
          'name' => DEFAULT_CERT_NAME,
          'status' => custom_pkcs_list.any? { |e| e['status'] == 'default' } ? 'validate' : 'default'
        }
      end,
      *custom_pkcs_list
    ].compact.reverse
  end

  def new
    @cert_record = CertFormRecord.new
  end

  def create
    @cert_record = CertFormRecord.new(**cert_params)

    if (@encrypted_config.value && @encrypted_config.value['custom']&.any? { |e| e['name'] == @cert_record.name }) ||
       @cert_record.name == DEFAULT_CERT_NAME

      @cert_record.errors.add(:name, 'already exists')

      return render turbo_stream: turbo_stream.replace(:modal, template: 'esign_settings/new'),
                    status: :unprocessable_entity
    end

    save_new_cert!(@encrypted_config, @cert_record)

    redirect_to settings_esign_path, notice: 'Certificate has been successfully added!'
  rescue OpenSSL::PKCS12::PKCS12Error
    @cert_record.errors.add(:password, "is invalid. Make sure you're uploading a valid .p12 file")

    render turbo_stream: turbo_stream.replace(:modal, template: 'esign_settings/new'), status: :unprocessable_entity
  end

  def update
    @encrypted_config.value['custom'].each { |e| e['status'] = 'validate' }

    custom_cert_data = @encrypted_config.value['custom'].find { |e| e['name'] == params[:name] }
    custom_cert_data['status'] = 'default' if custom_cert_data

    @encrypted_config.save!

    redirect_to settings_esign_path, notice: 'Default certificate has been selected'
  end

  def destroy
    @encrypted_config.value['custom'].reject! { |e| e['name'] == params[:name] }

    @encrypted_config.save!

    redirect_to settings_esign_path, notice: 'Certificate has been removed'
  end

  private

  def load_encrypted_config
    @encrypted_config = EncryptedConfig.find_or_initialize_by(account: current_account,
                                                              key: EncryptedConfig::ESIGN_CERTS_KEY)
  end

  def save_new_cert!(cert_configs, cert_record)
    pkcs = OpenSSL::PKCS12.new(cert_record.file.read, cert_record.password)

    cert_configs.value ||= {}
    cert_configs.value['custom'] ||= []
    cert_configs.value['custom'].each { |e| e['status'] = 'validate' }
    cert_configs.value['custom'] << {
      data: Base64.urlsafe_encode64(pkcs.to_der),
      password: cert_record.password,
      name: cert_record.name,
      status: 'default'
    }

    cert_configs.save!
  end

  def cert_params
    return {} if params[:esign_settings_controller_cert_form_record].blank?

    params.require(:esign_settings_controller_cert_form_record).permit(:name, :file, :password)
  end
end

app/views/esign_settings/new.html.erb
<%= render 'shared/turbo_modal', title: 'Upload Certificate' do %>
  <%= form_for @cert_record, url: settings_esign_path, html: { class: 'space-y-4', enctype: 'multipart/form-data' }, data: { turbo_frame: :_top } do |f| %>
    <div class="space-y-2">
      <div class="form-control">
        <%= f.label :name, class: 'label' %>
        <%= f.text_field :name, required: true, class: 'base-input' %>
      </div>
      <div class="form-control">
        <%= f.label :file, class: 'label' %>
        <%= f.file_field :file, required: true %>
        <label class="label">
          <span class="label-text-alt">Use a valid .der, .p12 or .pfx file.</span>
        </label>
      </div>
      <div class="form-control">
        <%= f.label :password, 'Password (optional)', class: 'label' %>
        <%= f.password_field :password, class: 'base-input' %>
      </div>
    </div>
    <div class="form-control pt-2">
      <%= f.button button_title, class: 'base-button' %>
    </div>
  <% end %>
<% end %>

app/views/esign_settings/show.html.erb
<div class="flex-wrap space-y-4 md:flex md:flex-nowrap md:space-y-0 md:space-x-10">
  <%= render 'shared/settings_nav' %>
  <div class="md:flex-grow">
    <div class="max-w-xl">
      <h1 class="text-4xl font-bold mb-4">PDF Signature</h1>
      <div id="result">
        <p class="mb-2">
          Upload signed PDF file to validate its signature:
        </p>
      </div>
      <%= form_for '', url: verify_pdf_signature_index_path, method: :post, html: { enctype: 'multipart/form-data' } do |f| %>
        <%= f.button type: 'submit', class: 'flex' do %>
          <div class="disabled mb-3">
            <%= svg_icon('loader', class: 'w-5 h-5 animate-spin inline') %>
            Analyzing...
          </div>
        <% end %>
        <file-dropzone data-is-direct-upload="false" data-name="verify_attachments" data-submit-on-upload="true" class="w-full">
          <label for="file" class="w-full block h-32 relative bg-base-200 hover:bg-base-200/70 rounded-md border border-base-content border-dashed">
            <div class="absolute top-0 right-0 left-0 bottom-0 flex items-center justify-center">
              <div class="flex flex-col items-center">
                <span data-target="file-dropzone.icon">
                  <%= svg_icon('cloud_upload', class: 'w-10 h-10') %>
                </span>
                <span data-target="file-dropzone.loading" class="hidden">
                  <%= svg_icon('loader', class: 'w-10 h-10 animate-spin') %>
                </span>
                <div class="font-medium mb-1">
                  Verify Signed PDF
                </div>
                <div class="text-xs">
                  <span class="font-medium">Click to upload</span> or drag and drop files
                </div>
              </div>
              <input id="file" name="files[]" class="hidden" data-action="change:file-dropzone#onSelectFiles" data-target="file-dropzone.input" type="file" accept="application/pdf" multiple>
            </div>
          </label>
        </file-dropzone>
      <% end %>
    </div>
    <div class="flex justify-between items-end mb-4 mt-8">
      <h2 class="text-3xl font-bold">Signing Certificates</h2>
      <% if can?(:create, @encrypted_config) %>
        <%= link_to new_settings_esign_path, class: 'btn btn-primary btn-md', data: { turbo_frame: 'modal' } do %>
          <%= svg_icon('plus', class: 'w-6 h-6') %>
          <span>Upload Cert</span>
        <% end %>
      <% end %>
    </div>
    <%= render 'alert' %>
    <div class="overflow-x-auto">
      <table class="table w-full table-lg rounded-b-none overflow-hidden">
        <thead class="bg-base-200">
          <tr class="text-neutral uppercase">
            <th>
              Name
            </th>
            <th>
              Valid To
            </th>
            <th>
              Status
            </th>
            <th class="text-right" width="1px">
            </th>
          </tr>
        </thead>
        <tbody>
          <% @pkcs_list.each do |item| %>
            <tr scope="row" class="group">
              <td>
                <%= item['name'] %>
              </td>
              <td>
                <%= l(item['pkcs'].certificate.not_after.to_date, format: :long, locale: current_account.locale) %>
              </td>
              <td>
                <% if item['status'] == 'default' %>
                  <span class="badge badge-lg badge-info badge-outline">
                    <%= item['status'] %>
                  </span>
                <% elsif can?(:update, @encrypted_config) %>
                  <%= button_to settings_esign_path, method: :put, params: { name: item['name'] }, class: 'btn btn-outline btn-neutral btn-xs whitespace-nowrap', title: 'Delete', data: { turbo_confirm: 'Are you sure?' } do %>
                    Make Default
                  <% end %>
                <% end %>
              </td>
              <td>
                <% if item['name'] != EsignSettingsController::DEFAULT_CERT_NAME && item['status'] != 'default' &&  can?(:destroy, @encrypted_config) %>
                  <%= button_to settings_esign_path, params: { name: item['name'] }, method: :delete, class: 'btn btn-outline btn-error btn-xs', title: 'Delete', data: { turbo_confirm: 'Are you sure?' } do %>
                    Remove
                  <% end %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
    <% encrypted_config = EncryptedConfig.find_or_initialize_by(account: current_account, key: EncryptedConfig::TIMESTAMP_SERVER_URL_KEY) %>
    <% if !Docuseal.multitenant? && can?(:manage, encrypted_config) %>
      <div class="flex-grow max-w-xl">
        <div class="flex justify-between items-end mb-4 mt-8">
          <h2 class="text-3xl font-bold">Timestamp Server</h2>
        </div>
        <%= form_for encrypted_config, url: timestamp_server_index_path, method: :post, html: { autocomplete: 'off', class: 'space-y-4' } do |f| %>
          <div class="form-control">
            <%= f.label :value, class: 'label' do %>
              <span class="flex items-center space-x-1">
                <span>
                  Timeserver URL
                </span>
                <span class="tooltip" data-tip="URL of the trusted RFC 3161 timeserver to be used to generate timestamp signatures.">
                  <%= svg_icon('info_circle', class: 'w-4 h-4') %>
                </span>
              </span>
            <% end %>
            <%= f.url_field :value, autocomplete: 'off', class: 'base-input', placeholder: 'URL (optional)' %>
          </div>
          <div class="form-control pt-2">
            <%= f.button button_title(title: 'Save', disabled_with: 'Updating'), class: 'base-button' %>
          </div>
        <% end %>
      </div>
    <% end %>
    <% account_config = AccountConfig.where(account: current_account, key: AccountConfig::ESIGNING_PREFERENCE_KEY).first_or_initialize(value: 'multiple') %>
    <% if can?(:manage, account_config) %>
      <div class="px-1 mt-8 max-w-xl">
        <div class="flex justify-between items-end mb-4 mt-8">
          <h2 class="text-3xl font-bold">Preferences</h2>
        </div>
        <% if can?(:manage, account_config) %>
          <%= form_for account_config, url: account_configs_path, method: :post do |f| %>
            <%= f.hidden_field :key %>
            <div class="flex items-center justify-between py-2.5">
              <span>
                Apply multiple PDF digital signatures in the document per each signer
              </span>
              <%= f.check_box :value, { class: 'toggle', checked: account_config.value == 'multiple', onchange: 'this.form.requestSubmit()' }, 'multiple', 'single' %>
            </div>
          <% end %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>