config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  mount LetterOpenerWeb::Engine, at: '/letter_opener' if Rails.env.development?
  mount Sidekiq::Web => '/sidekiq' if defined?(Sidekiq)

  root 'dashboard#index'

  get 'up' => 'rails/health#show'

  devise_for :users,
             path: '/', only: %i[sessions passwords omniauth_callbacks],
             controllers: begin
               options = { sessions: 'sessions', passwords: 'passwords' }
               options[:omniauth_callbacks] = 'omniauth_callbacks' if User.devise_modules.include?(:omniauthable)
               options
             end

  devise_scope :user do
    resource :invitation, only: %i[update] do
      get '' => :edit
    end
  end

  namespace :api, defaults: { format: :json } do
    resources :attachments, only: %i[create]
    resources :submitters_autocomplete, only: %i[index]
    resources :template_folders_autocomplete, only: %i[index]
    resources :submitter_email_clicks, only: %i[create]
    resources :submitter_form_views, only: %i[create]
    resources :submitters, only: %i[index show update]
    resources :submissions, only: %i[index show create destroy] do
      collection do
        resources :emails, only: %i[create], controller: 'submissions', as: :submissions_emails
      end
    end
    resources :templates, only: %i[update show index destroy] do
      resources :clone, only: %i[create], controller: 'templates_clone'
      resources :submissions, only: %i[index create]
      resources :documents, only: %i[create], controller: 'templates_documents'
    end
  end

  resources :verify_pdf_signature, only: %i[create]
  resource :mfa_setup, only: %i[show new edit create destroy], controller: 'mfa_setup'
  resources :account_configs, only: %i[create]
  resources :user_configs, only: %i[create]
  resources :encrypted_user_configs, only: %i[destroy]
  resources :timestamp_server, only: %i[create]
  resources :dashboard, only: %i[index]
  resources :setup, only: %i[index create]
  resource :newsletter, only: %i[show update]
  resources :enquiries, only: %i[create]
  resources :users, only: %i[new create edit update destroy]
  resource :user_signature, only: %i[edit update destroy]
  resources :submissions, only: %i[show destroy]
  resources :console_redirect, only: %i[index]
  resource :testing_account, only: %i[show destroy]
  resources :testing_api_settings, only: %i[index]
  resource :templates_upload, only: %i[create]
  authenticated do
    resource :templates_upload, only: %i[show], path: 'new'
  end
  resources :templates_archived, only: %i[index], path: 'archived'
  resources :folders, only: %i[show edit update destroy], controller: 'template_folders'
  resources :template_sharings_testing, only: %i[create]
  resources :templates, only: %i[new create edit show destroy] do
    resources :restore, only: %i[create], controller: 'templates_restore'
    resources :archived, only: %i[index], controller: 'templates_archived_submissions'
    resources :submissions, only: %i[new create]
    resource :folder, only: %i[edit update], controller: 'templates_folders'
    resource :preview, only: %i[show], controller: 'templates_preview'
    resource :code_modal, only: %i[show], controller: 'templates_code_modal'
    resources :submissions_export, only: %i[index new]
  end
  resources :preview_document_page, only: %i[show], path: '/preview/:signed_uuid'
  resource :blobs_proxy, only: %i[show], path: '/blobs_proxy/:signed_uuid/*filename',
                         controller: 'api/active_storage_blobs_proxy'

  if Docuseal.multitenant?
    resource :blobs_proxy_legacy, only: %i[show],
                                  path: '/blobs/proxy/:signed_id/*filename',
                                  controller: 'api/active_storage_blobs_proxy_legacy',
                                  as: :rails_blob
    get '/disk/:encoded_key/*filename' => 'active_storage/disk#show', as: :rails_disk_service
    put '/disk/:encoded_token' => 'active_storage/disk#update', as: :update_rails_disk_service
    post '/direct_uploads' => 'active_storage/direct_uploads#create', as: :rails_direct_uploads
  end

  resources :start_form, only: %i[show update], path: 'd', param: 'slug' do
    get :completed
  end

  resources :submit_form, only: %i[], path: '' do
    get :success, on: :collection
  end

  resources :submit_form, only: %i[show update], path: 's', param: 'slug' do
    get :completed
  end

  resources :submissions_preview, only: %i[show], path: 'e', param: 'slug' do
    get :completed
  end

  resources :send_submission_email, only: %i[create] do
    get :success, on: :collection
  end

  resources :submitters, only: %i[], param: 'slug' do
    resources :download, only: %i[index], controller: 'submissions_download'
    resources :send_email, only: %i[create], controller: 'submitters_send_email'
    resources :debug, only: %i[index], controller: 'submissions_debug' if Rails.env.development?
  end

  scope '/settings', as: :settings do
    unless Docuseal.multitenant?
      resources :storage, only: %i[index create], controller: 'storage_settings'
      resources :email, only: %i[index create], controller: 'email_smtp_settings'
      resources :sms, only: %i[index], controller: 'sms_settings'
      resources :sso, only: %i[index], controller: 'sso_settings'
    end
    resources :notifications, only: %i[index create], controller: 'notifications_settings'
    resource :esign, only: %i[show create new update destroy], controller: 'esign_settings'
    resources :users, only: %i[index]
    resource :personalization, only: %i[show create], controller: 'personalization_settings'
    resources :api, only: %i[index create], controller: 'api_settings'
    resource :webhooks, only: %i[show create update], controller: 'webhook_settings'
    resource :account, only: %i[show update destroy]
    resources :profile, only: %i[index] do
      collection do
        patch :update_contact
        patch :update_password
        patch :update_app_url
      end
    end
  end

  ActiveSupport.run_load_hooks(:routes, self)
end

app/views/shared/_attribution.html.erb
<%= render 'shared/powered_by', with_counter: local_assigns[:with_counter], link_path: local_assigns[:link_path] %>

app/views/shared/_clipboard_copy.html.erb
<clipboard-copy data-text="<%= text %>">
  <label class="<%= local_assigns[:class] %>">
    <input type="radio" class="peer hidden">
    <span class="peer-checked:hidden flex items-center space-x-2">
      <%= svg_icon(local_assigns[:icon] || 'link', class: local_assigns[:icon_class] || 'w-6 h-6 text-white') %>
      <span class="hidden md:inline">
        <%= local_assigns[:copy_title] || 'Copy' %>
      </span>
      <% if local_assigns[:copy_title_md] %>
        <span class="inline md:hidden">
          <%= local_assigns[:copy_title_md] %>
        </span>
      <% end %>
    </span>
    <span class="hidden peer-checked:flex items-center space-x-2">
      <%= svg_icon(local_assigns[:copied_icon] || 'clipboard_copy', class: local_assigns[:icon_class] || 'w-6 h-6 text-white') %>
      <span class="hidden md:inline">
        <%= local_assigns[:copied_title] || 'Copied' %>
      </span>
      <% if local_assigns[:copied_title_md] %>
        <span class="inline md:hidden">
          <%= local_assigns[:copied_title_md] %>
        </span>
      <% end %>
    </span>
  </label>
</clipboard-copy>

app/views/shared/_demo_alert.html.erb
<div class="mx-auto mt-1.5">
  <div class="py-3 rounded-2xl flex items-center justify-between mx-4 md:mx-0">
    <div class="w-full text-center">
      <span class="font-bold">Demo Environment</span>
      <br>
      <a href="<%= new_template_path %>" data-turbo-frame="modal" class="inline underline font-medium">Create a new template</a> document form or
      <a href="<%= start_form_url(slug: ::Template.first&.slug) %>" target="_blank" class="inline underline font-medium">submit the existing one</a> 😊
    </div>
  </div>
</div>

app/views/shared/_field_error.html.erb
<% 'input-error' %>
<span class="label-text-alt text-red-400 mt-1">
  <%= message %>
</span>

app/views/shared/_github_button.html.erb
<a href="https://github.com/docusealco/docuseal" class="btn btn-neutral btn-sm btn-outline inline-flex items-center justify-center" target="_blank" alt="Star on GitHub" style="height: 37px">
  <span>
    <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24">
      <path fill="currentColor" d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
    </svg>
  </span>
  <span class="flex">
    <span class="hidden lg:block">Star on&nbsp</span>GitHub
  </span>
</a>

app/views/shared/_meta.html.erb
<% if Docuseal.demo? || (request.path != '/' && !devise_controller?) %>
  <meta name="robots" content="noindex">
<% end %>
<meta name="description" content="Open source, self-hosted tool to streamline document filling and signing. Create custom PDF forms to complete and sign with an easy to use online tool.">
<meta property="og:title" content="DocuSeal | Open Source Document Filling and Signing">
<meta property="og:description" content="Open source, self-hosted tool to streamline document filling and signing. Create custom PDF forms to complete and sign with an easy to use online tool.">
<meta property="og:type" content="website">
<meta property="og:url" content="<%= root_url %>">
<meta property="og:site_name" content="DocuSeal">
<meta property="og:image" content="<%= image_pack_url('images/preview.png') %>">
<meta property="og:image:width" content="800">
<meta property="og:image:height" content="800">
<meta name="twitter:image" content="<%= image_pack_url('images/preview.png') %>">
<meta name="twitter:card" content="summary">
<meta name="twitter:creator" content="@docusealco">
<meta name="twitter:site" content="@docusealco">
<meta name="twitter:title" content="DocuSeal | Open Source Document Filling and Signing">
<meta name="twitter:description" content="Open source, self-hosted tool to streamline document filling and signing. Create custom PDF forms to complete and sign with an easy to use online tool.">
<link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
<link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
<link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
<link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
<meta name="theme-color" content="#faf7f5">

app/views/shared/_navbar.html.erb
<div class="max-w-6xl mb-4 mx-auto px-4 md:px-2 py-3 flex items-center justify-between">
  <div class="flex items-center space-x-4">
    <a href="<%= root_path %>" class="text-2xl font-bold items-center flex space-x-2">
      <%= render 'shared/title' %>
    </a>
    <span class="hidden sm:inline">
      <%= render 'shared/github' %>
    </span>
  </div>
  <% if signed_in? %>
    <div class="space-x-4 flex items-center">
      <% if Docuseal.demo? %>
        <a href="https://docuseal.co/sign_up" class="btn btn-neutral btn-sm btn-outline inline-flex items-center justify-center" style="height: 37px">
          Sign Up
        </a>
        <span class="hidden sm:inline">
          <%= render 'shared/github_button' %>
        </span>
      <% else %>
        <div class="flex items-center justify-center space-x-4 mr-1">
          <%= render 'shared/navbar_buttons' %>
          <%= link_to 'Settings', settings_profile_index_path, class: 'hidden md:inline-flex font-medium text-lg' %>
        </div>
      <% end %>
      <div class="dropdown dropdown-end">
        <label tabindex="0" class="cursor-pointer bg-base-content text-purple-300 rounded-full p-2 w-9 justify-center flex">
          <span class="text-sm align-text-top"><%= current_user.initials %></span>
        </label>
        <ul tabindex="0" class="z-10 dropdown-content p-2 mt-2 shadow menu text-base bg-base-100 rounded-box whitespace-nowrap text-right">
          <li>
            <%= link_to settings_profile_index_path, class: 'flex items-center' do %>
              <%= svg_icon('adjustments', class: 'w-5 h-5 stroke-2') %>
              <span class="mr-1">Profile</span>
            <% end %>
          </li>
          <% if !Docuseal.demo? && can?(:manage, EncryptedConfig) %>
            <li>
              <%= link_to Docuseal.multitenant? ? console_redirect_index_path : Docuseal::CONSOLE_URL, data: { prefetch: false }, class: 'flex items-center' do %>
                <%= svg_icon('terminal', class: 'w-5 h-5 stroke-2') %>
                Console
              <% end %>
            </li>
          <% end %>
          <% if can?(:read, EncryptedConfig.new(key: EncryptedConfig::ESIGN_CERTS_KEY, account: current_account)) %>
            <li>
              <%= link_to settings_esign_path, class: 'flex items-center' do %>
                <%= svg_icon('zoom_check', class: 'w-5 h-5 stroke-2') %>
                <span class="mr-1">Verify PDF</span>
              <% end %>
            </li>
          <% end %>
          <li>
            <%= button_to destroy_user_session_path, method: :delete, data: { turbo: false }, class: 'flex items-center' do %>
              <%= svg_icon('logout', class: 'w-5 h-5 stroke-2 mr-2 inline') %>
              <span class="mr-1">Sign out</span>
            <% end %>
          </li>
        </ul>
      </div>
    </div>
  <% else %>
    <div class="flex space-x-2">
      <% if request.path != new_user_session_path %>
        <%= link_to new_user_session_path, class: 'font-medium text-lg' do %>
          <span class="flex items-center justify-center space-x-1">
            <%= svg_icon('login', class: 'w-6 h-6') %>
            <span>Sign in</span>
          </span>
        <% end %>
      <% end %>
      <% if Docuseal.multitenant? && !request.path.in?([registration_path, new_registration_path]) %>
        <%= link_to registration_path, class: 'btn btn-neutral btn-sm btn-outline' do %>
          <span class="flex items-center justify-center space-x-1">
            <span class="hidden sm:block">Create free Account</span>
            <span class="md:hidden">Sign Up</span>
          </span>
        <% end %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_navbar_buttons.html.erb
<%= link_to Docuseal.multitenant? ? console_redirect_index_path(redir: "#{Docuseal::CONSOLE_URL}/plans") : "#{Docuseal::CLOUD_URL}/sign_up?#{{ redir: "#{Docuseal::CONSOLE_URL}/on_premise" }.to_query}", class: 'hidden md:inline-flex btn btn-warning btn-sm', data: { prefetch: false } do %>
  Upgrade
<% end %>
<% if signed_in? && current_user != true_user %>
  <span class="hidden md:inline-flex h-3 border-r border-base-content"></span>
  <%= render 'shared/test_alert' %>
<% end %>
<span class="hidden md:inline-flex h-3 border-r border-base-content"></span>

app/views/shared/_pagination.html.erb
<% link = pagy_link_proc(@pagy) %>
<% if @pagy.pages > 1 %>
  <div class="flex my-6 justify-center md:justify-between">
    <div class="hidden md:block text-sm">
      <%= @pagy.from %>-<%= local_assigns.fetch(:to, @pagy.to) %> of <%= local_assigns.fetch(:count, @pagy.count) %> <%= local_assigns[:items_name] || 'items' %>
      <%= local_assigns[:left_additional_html] %>
    </div>
    <div class="join">
      <% if @pagy.prev %>
        <%== link.call(@pagy.prev, '«', 'class="join-item btn min-h-full h-10"') %>
      <% else %>
        <span class="join-item btn btn-disabled !bg-base-200 min-h-full h-10">«</span>
      <% end %>
      <span class="join-item btn uppercase min-h-full h-10">
        Page <%= @pagy.page %>
      </span>
      <% if @pagy.next %>
        <%== link.call(@pagy.next, '»', 'class="join-item btn min-h-full h-10"') %>
      <% else %>
        <span class="join-item btn btn-disabled !bg-base-200 min-h-full h-10">»</span>
      <% end %>
    </div>
  </div>
<% end %>

app/views/shared/_powered_by.html.erb
<div class="text-center px-2">
  <% if local_assigns[:with_counter] %>
    <% count = Submitter.where.not(completed_at: nil).distinct.count(:submission_id) %>
    <% if count > 1 %>
      <b><%= count %></b> documents signed with
    <% else %>
      Powered by
    <% end %>
  <% else %>
    Powered by
  <% end %>
  <a href="<%= Docuseal::PRODUCT_URL %><%= local_assigns[:link_path] %>" class="underline"><%= Docuseal.product_name %></a> - open source documents software
</div>

app/views/shared/_search_input.html.erb
<form action="<%= url_for %>" method="get" class="items-center hidden md:flex">
  <% if params[:status].present? %>
    <input name="status" value="<%= params[:status] %>" class="hidden">
  <% end %>
  <% if params[:q].present? %>
    <div class="relative">
      <a href="<%= url_for(params.to_unsafe_h.except(:q)) %>" title="Clear" class="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-auto text-neutral text-2xl font-extralight">
        &times;
      </a>
    </div>
  <% end %>
  <input id="search" name="q" value="<%= params[:q] %>" class="input input-ghost text-lg pr-10 -mr-12 <%= 'pl-8 input-outlined' if params[:q].present? %>">
  <button type="submit" title="Search" class="btn btn-ghost btn-circle" onclick="window.search.value || document.activeElement === window.search ? null : [event.preventDefault(), window.search.focus()]">
    <span class="enabled">
      <%= svg_icon('search', class: 'w-6 h-6 stroke-2') %>
    </span>
    <span class="disabled">
      <%= svg_icon('loader', class: 'w-5 h-5 animate-spin') %>
    </span>
  </button>
</form>

app/views/shared/_test_alert.html.erb
<% if signed_in? && current_user != true_user && current_account.testing? %>
  <div class="alert py-1 text-sm font-medium gap-x-2 flex whitespace-nowrap">
    <a href="<%= testing_api_settings_path %>" data-turbo-frame="modal" class="link font-semibold flex">
      <%= svg_icon('code_circle', class: 'w-5 h-5 mr-1') %>Testing Environment
    </a>
    <span>
      |
    </span>
    <%= button_to testing_account_path, method: :delete, class: 'inline flex' do %>
      <% title = capture do %>
        <span class="link">Exit</span>
        <span>&times;</span>
      <% end %>
      <%= button_title(title:, disabled_with: 'Leave') %>
    <% end %>
  </div>
<% end %>

app/views/shared/_test_mode_toggle.html.erb
<% if can?(:manage, EncryptedConfig) || (current_user != true_user && current_account.testing?) %>
  <%= form_for '', url: testing_account_path, method: current_account.testing? ? :delete : :get, html: { class: 'flex' } do |f| %>
    <label class="flex items-center justify-between py-2.5" for="testing_toggle">
      <span class="mr-2 text-lg">
        Test Environment
      </span>
      <%= f.check_box :testing_toggle, class: 'toggle', checked: current_account.testing?, onchange: 'this.form.requestSubmit()' %>
    </label>
  <% end %>
<% end %>